[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@v2-core/=lib/v2-core",
]

[invariant]
runs = 400
depth = 30

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
